#
# Module manifest for module 'Lansweeper-PS'
#
# Generated by: Marcus Dean
#
# Generated on: 7/18/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Lansweeper-PS.psm1'

# Version number of this module.
ModuleVersion = '1.30.04'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'f475c9cd-0a05-4a37-b8d2-feffff6b25bd'

# Author of this module
Author = 'Marcus Dean'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '2019 Marcus Dean'

# Description of the functionality provided by this module
Description = 'Provides a wrapper for dbatools to query Lansweeper SQL database to pull information about assets and users'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = 'dbatools'

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-LSAsset', 'Get-LSAssetCustom', 'Get-LSADComputer', 'Get-LSUser', 
               'Get-LSComputerObject', 'Get-LSLinuxSystem', 'Get-LSDisks', 
               'Get-LSLinuxVolumes', 'Get-LSWindowsSoftware', 'Get-LSMacSoftware'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'LSComputerObjectQuery.txt', 'LSWindowsSoftwareQuery.txt', 'LSMacSoftwareQuery.txt'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Lansweeper', 'Automation', 'Reports', 'Windows')

        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/MIT'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/marcus-dean/Lansweeper-PS'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
                        -Version 1.30.04: Added modules for querying windows and mac software, added AssetName as a parameter for Get-LSDisks
                        -Version 1.3: Added manual verification and installation of dbatools to avoid error on importing because 
                        dbatools took slightly too long and would cause the module import to error out
                        '

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/marcus-dean/Lansweeper-PS/blob/master/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}